// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zw9xsRrC_fNz_5WcKuj1x9LeganTNlM',
    appId: '1:742394536754:web:49476573e4792d06752d2b',
    messagingSenderId: '742394536754',
    projectId: 'fir-tut-6b4bd',
    authDomain: 'fir-tut-6b4bd.firebaseapp.com',
    storageBucket: 'fir-tut-6b4bd.appspot.com',
    measurementId: 'G-0YKZJZJDLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMRYohQpmMsvEJJDS_bVOrnmcW5R2e_o',
    appId: '1:742394536754:android:f4680ba59612ed18752d2b',
    messagingSenderId: '742394536754',
    projectId: 'fir-tut-6b4bd',
    storageBucket: 'fir-tut-6b4bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpWJqOslT78lZxlb78HakcGB7XyrsSuUA',
    appId: '1:742394536754:ios:264feff44b75b8d8752d2b',
    messagingSenderId: '742394536754',
    projectId: 'fir-tut-6b4bd',
    storageBucket: 'fir-tut-6b4bd.appspot.com',
    iosBundleId: 'com.example.tut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpWJqOslT78lZxlb78HakcGB7XyrsSuUA',
    appId: '1:742394536754:ios:264feff44b75b8d8752d2b',
    messagingSenderId: '742394536754',
    projectId: 'fir-tut-6b4bd',
    storageBucket: 'fir-tut-6b4bd.appspot.com',
    iosBundleId: 'com.example.tut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2zw9xsRrC_fNz_5WcKuj1x9LeganTNlM',
    appId: '1:742394536754:web:9e12c7cd48c53af2752d2b',
    messagingSenderId: '742394536754',
    projectId: 'fir-tut-6b4bd',
    authDomain: 'fir-tut-6b4bd.firebaseapp.com',
    storageBucket: 'fir-tut-6b4bd.appspot.com',
    measurementId: 'G-JGMHNKBS0F',
  );

}